version: '3.8'
services:
  db:
    container_name: db
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tiramisu
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    container_name: backend
    build: backend/
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: tiramisu

  frontend:
    container_name: frontend
    build: frontend/
    depends_on:
      - backend
    ports:
      - 5000:5000
